//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Privet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Абв.
    /// </summary>
    //  *** Start programmer edit section *** (Абв CustomAttributes)

    //  *** End programmer edit section *** (Абв CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АбвE", new string[] {
            "Гд as \'Гд\'"})]
    [View("АбвL", new string[] {
            "Гд as \'Гд\'"})]
    public class Абв : ICSSoft.STORMNET.DataObject
    {
        
        private string fГд;
        
        //  *** Start programmer edit section *** (Абв CustomMembers)

        //  *** End programmer edit section *** (Абв CustomMembers)

        
        /// <summary>
        /// Гд.
        /// </summary>
        //  *** Start programmer edit section *** (Абв.Гд CustomAttributes)

        //  *** End programmer edit section *** (Абв.Гд CustomAttributes)
        [StrLen(255)]
        public virtual string Гд
        {
            get
            {
                //  *** Start programmer edit section *** (Абв.Гд Get start)

                //  *** End programmer edit section *** (Абв.Гд Get start)
                string result = this.fГд;
                //  *** Start programmer edit section *** (Абв.Гд Get end)

                //  *** End programmer edit section *** (Абв.Гд Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Абв.Гд Set start)

                //  *** End programmer edit section *** (Абв.Гд Set start)
                this.fГд = value;
                //  *** Start programmer edit section *** (Абв.Гд Set end)

                //  *** End programmer edit section *** (Абв.Гд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АбвE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АбвE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АбвE", typeof(IIS.Privet.Абв));
                }
            }
            
            /// <summary>
            /// "АбвL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АбвL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АбвL", typeof(IIS.Privet.Абв));
                }
            }
        }
    }
}
